name: Persistent 24/7 SSHX Server

on:
  workflow_dispatch:
  repository_dispatch:
    types: [restart_persistent_session]

env:
  IMAGE_FILE: "/root/disk.img"
  MOUNT_POINT: "/mnt/persistent_disk"
  PERSISTENT_DIR: "${{ env.MOUNT_POINT }}/data"

jobs:
  persistent-server:
    runs-on: ubuntu-latest
    timeout-minutes: 355  # 5h 55m (restart before 6h limit)

    steps:
    # STEP 1: Download Previous Disk Image
    - name: Download persistent disk image
      uses: actions/download-artifact@v4
      with:
        name: persistent-disk-image
        path: /root/
      continue-on-error: true

    # STEP 2: Setup Persistent Storage
    - name: Setup persistent storage system
      run: |
        # Create disk image if it doesn't exist (first run)
        if [ ! -f "${{ env.IMAGE_FILE }}" ]; then
            echo "Creating new 10GB persistent disk image..."
            dd if=/dev/zero of=${{ env.IMAGE_FILE}} bs=1M count=10240
            mkfs.ext4 ${{ env.IMAGE_FILE}}
        fi

        # Mount the disk image
        mkdir -p ${{ env.MOUNT_POINT }}
        mount -o loop ${{ env.IMAGE_FILE}} ${{ env.MOUNT_POINT}}

        # Setup directories
        mkdir -p ${{ env.PERSISTENT_DIR }}

        # Bind mount to make it available system-wide
        mount --bind ${{ env.PERSISTENT_DIR }} /persistent

        # Copy essential files if first run
        if [ ! -f "${{ env.MOUNT_POINT }}/.initialized" ]; then
            echo "Initializing persistent storage..."
            cp -r /etc/skel/* ${{ env.PERSISTENT_DIR }}/
            cp -r /root/* ${{ env.PERSISTENT_DIR }}/
            touch ${{ env.MOUNT_POINT }}/.initialized
        fi

        echo "Persistent storage mounted at /persistent"

    # STEP 3: Install & Configure System
    - name: Install and configure system
      run: |
        # Update package lists
        apt-get update

        # Install essential tools
        apt-get install -y \
            docker.io \
            python3 \
            nodejs \
            npm \
            git \
            build-essential

        # Install custom software to persistent storage
        cd /persistent
        git clone https://github.com/your-repo/your-project.git || true

        # Setup services (will persist across restarts)
        cat > /persistent/startup.sh << 'EOF'
        #!/bin/bash
        # This runs every time the system starts
        echo "Starting persistent services..."
        # Add your startup commands here
        # docker-compose up -d
        # node server.js &
        EOF

        chmod +x /persistent/startup.sh
        /persistent/startup.sh

    # STEP 4: Start Auto-Restart System
    - name: Setup auto-restart system
      run: |
        cat > /persistent/restart_system.sh << 'EOF'
        #!/bin/bash
        # Wait 5 hours 50 minutes
        sleep 21000

        # Save current state
        sync
        umount ${{ env.MOUNT_POINT }}

        # Upload disk image
        curl -s \
          -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://uploads.github.com/repos/${{ github.repository }}/actions/artifacts \
          -F "name=persistent-disk-image" \
          -F "data=@${{ env.IMAGE_FILE }}" > /dev/null

        # Trigger restart
        curl -s -X POST \
          -H "Authorization: token ${{ secrets.AUTO_TRIGGER_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "restart_persistent_session"}'
        EOF

        chmod +x /persistent/restart_system.sh
        /persistent/restart_system.sh &

    # STEP 5: Launch SSHX Terminal
    - name: Launch Persistent SSHX Terminal
      run: |
        echo "=================================================="
        echo "🚀 PERSISTENT ROOT SERVER - NO DATA LOSS"
        echo "=================================================="
        echo "All data is saved in: /persistent/"
        echo "Installed software: /persistent/usr/"
        echo "System will auto-restart every 6 hours"
        echo "=================================================="
        
        # Start SSHX session
        curl -fsSL https://sshx.io/get.sh | sh

    # STEP 6: Final Save & Restart
    - name: Save state and restart
      if: always()
      run: |
        echo "Saving final state and restarting..."
        sync
        umount ${{ env.MOUNT_POINT }} || true
        
        # Upload final disk state
        curl -s \
          -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://uploads.github.com/repos/${{ github.repository }}/actions/artifacts \
          -F "name=persistent-disk-image" \
          -F "data=@${{ env.IMAGE_FILE }}" > /dev/null

        # Force restart
        curl -s -X POST \
          -H "Authorization: token ${{ secrets.AUTO_TRIGGER_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "restart_persistent_session"}'
